# Generated by Django 5.2 on 2026-04-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_update_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
